### ISSUE TITLE
sealPir仅仅支持8192安全参数？

### ISSUE THREAD

**Issue by Yinbenxin** [secretflow/psi#109]
```
struct TestParams {
  size_t batch_number;
  size_t element_number;
  size_t element_size = 288;
  size_t poly_degree = 8192;  // now only support 8192
};
```
在sealPir测试时发现在代码中说仅仅支持8192安全参数，这将导致密文长度过长，我尝试修改相关安全参数，并解决相关报错，但是计算结果错误。而在sealPir开源库中支持4096安全强度。想问一下：
1.出于什么原因仅支持8192安全参数。
2.是否能修改一些代码部分来支持其他安全参数？

**Comment by Jamie-Cui** [comment]
Hi 感谢提问，

1. 8192 安全参数是当初集成第三方代码时我们可以自己测试成功的参数，其他参数选择会有错误（例如 2048 等），由于规划愿意目前暂未支持其他参数
2. 是可以修改代码来支持其他安全参数的，如果感兴趣的话可以研究一下～

**Comment by Yinbenxin** [comment]
好的，感谢🙏
