### ISSUE TITLE
Seal PIR 与 Labeled PSI的疑问

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/psi#117]
### Issue Type

Others

### Source

source

### Secretflow Version

1.5.0.dev240319

### OS Platform and Distribution

centos 7.9

### Python version

3.10

### Bazel version

6.5.0

### GCC/Compiler version

11.2.1

### What happend and What you expected to happen.

```shell
老师，我有几个问题想请教下：
Q1 - 我们有Seal PIR测试案例链接吗，有Seal PIR封装接口的链接吗？
Q2 - 目前对外公布的pir_setup/pir_query方法都是基于Labeled PSI吗？
Q3 - 最后就是下面2个链接都失效了，有最新链接吗？
https://github.com/secretflow/spu/blob/main/libspu/pir/seal_pir_test.cc
https://github.com/secretflow/spu/blob/main/libspu/psi/core/labeled_psi/README.md
```

### Reproduction code to reproduce the issue.

```shell
无
```

**Comment by 6fj** [comment]
Hi @coderSun20201112 

1. SealPIR 目前没有暴露用户接口，目前只有单测：https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_pir_test.cc https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_mpir_test.cc。当然，我们正在做这方面的工作。
2. 对
3. https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_pir_test.cc https://github.com/secretflow/psi/blob/main/psi/apsi/README.md
