### ISSUE TITLE
关于unbalance psi中EcdhOprfPsiServer::FullEvaluate函数实现的疑问

### ISSUE THREAD

**Issue by shenpeilin** [secretflow/psi#129]
EcdhOprfPsiServer::FullEvaluate是unbalance psi调用链路中的一个函数，我关注到在这个函数中调用了oprf_server_->SimpleEvaluate(batch_items[0])来计算最后的oprf值，我想了解下这一实现是否存在问题，因为这看起来其实算出来的是一个HASH值。

按照https://www.secretflow.org.cn/en/docs/psi/v0.3.0beta/development/psi_protocol_intro#ecdh-oprf-based-psi
中的协议描述，此处似乎应该调用oprf_server_->FullEvaluate(batch_items[0])？

**Comment by 6fj** [comment]
hi @shenpeilin ,

SimpleEvaluate中最后一步会做一次hash，在此之前会做椭圆曲线上的点乘。

**Comment by shenpeilin** [comment]
@6fj 但按照文档的描述难道不是应该算H2(y,H1(y)^beta )?目前看起来实现上其实是H2(H1(y)^beta )是吗？

**Comment by 6fj** [comment]
> @6fj 但按照文档的描述难道不是应该算H2(y,H1(y)^beta )?目前看起来实现上其实是H2(H1(y)^beta )是吗？

文档的书写确实有点不清晰，我们会尽快调整文档，感谢！

**Comment by 6fj** [comment]
> EcdhOprfPsiServer::FullEvaluate是unbalance psi调用链路中的一个函数，我关注到在这个函数中调用了oprf_server_->SimpleEvaluate(batch_items[0])来计算最后的oprf值，我想了解下这一实现是否存在问题，因为这看起来其实算出来的是一个HASH值。
> 
> 按照https://www.secretflow.org.cn/en/docs/psi/v0.3.0beta/development/psi_protocol_intro#ecdh-oprf-based-psi 中的协议描述，此处似乎应该调用oprf_server_->FullEvaluate(batch_items[0])？

更新一下回答，这里不是在计算oprf值，oprf在线阶段的计算是client晚餐的

**Comment by 6fj** [comment]
目前文档的图片已经更新：https://www.secretflow.org.cn/en/docs/psi/v0.4.0.dev240521/development/psi_protocol_intro#ecdh-oprf-based-psi
