### ISSUE TITLE
[Bug]: import时报错illegal instruction

### ISSUE THREAD

**Issue by Fissure45** [secretflow/psi#140]
### Issue Type

Support

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.8.0b0

### OS Platform and Distribution

no matter

### Python Version

3.9

### Current Behavior?

在海光7185cpu上运行spu时，import spu spu.psi会报错illegal instruction (core dumped)，看起来缺少spu需要的指令集。在文档中我只看到需要avx2，该cpu是支持avx2的；能否提供更详细的spu所需指令集说明？

### Standalone code to reproduce the issue

```Python
--
```

**Comment by 6fj** [comment]
需要https://github.com/secretflow/spu/issues/167

**Comment by Fissure45** [comment]
我在另外一台缺少avx512指令集的服务器上可以正常运行spu。这台服务器的cpu信息如下：
![image-20240615](https://github.com/secretflow/psi/assets/149219675/3407fa8d-2cf4-4b90-8754-91731e4dea09)
同样import spu或者import spu.psi都不会报错；此外，我也没有在报错的服务器上使用apsi。

**Comment by 6fj** [comment]
hi @Fissure45 

我在寻找海光的机器验证你遇到的问题，请稍等～

**Comment by 6fj** [comment]
Hi @Fissure45 

我们没有海光7185，因此我在海光7265（avx, avx2）上进行了测试，没有发现你遇到的问题。
测试方式为

```
from spu import psi
```

**Comment by Fissure45** [comment]
这个问题似乎仅限7185发生。我们在7285上进行测试没有问题，但两台7185都出现了这个问题。

**Comment by 6fj** [comment]
由于我们没有海光7185，因此我们无法进行进一步处理。

如果可以的话，我们可能需要你这边提供机器。或者请向海光寻求技术支持。

**Comment by Fissure45** [comment]
好的，感谢帮助。现在环境已经迁移，我也无法进行更多测试；看起来这是特定型号的cpu问题。
