### ISSUE TITLE
[Bug]: 关于psi-anolis疑问

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/psi#145]
### Describe the bug

我通过官方docker镜像方式部署了EasyPSI整套工程，我有如下疑问：
疑问1：我解压之后得到secretflow-XXXX.tar，然后我导入该镜像后才发现该镜像名称是secretflow/psi-anolis，因此，我是不是可以认定EasyPSI镜像中没有secretflow工程，只有PSI工程？
疑问2：psi-anolis，是否支持ECDH_OPRF算法？
疑问3：如果psi-anolis支持ECDH_OPRF算法，哪里可以得到案例脚本？
疑问4：如果psi-anolis支持ECDH_OPRF算法，我该如何改造前端的React/Java工程，让其可以调用ECDH_OPRF算法？
疑问5：在ECDH_OPRF中，是只对求交列进行求哈希运算，还是对整条记录所有字段进行求哈希运算？

### Steps To Reproduce

无

### Expected behavior

无

### Version

0.2.0.dev240123

### Operating system

centos7

### Hardware Resources

8c16g

**Comment by lq0404510** [comment]
EasyPSI镜像中没有secretflow工程，执行任务时，kuscia会在容器内以进程形式拉起psi任务
psi-anolis平台目前不支持ECDH_OPRF算法

**Comment by 6fj** [comment]
hi @coderSun20201112 

1. Easy PSI 的 psi逻辑 并不是 secretflow 的 docker image，而是 psi 的 docker image
2. 支持
3. 本质上我们通过向 psi docker 传递一个 config 完成 psi 逻辑。请关注 https://github.com/secretflow/psi/tree/main/examples
4. 同上，你需要构建一个合理的 config 并 拉起 psi docker
5. 求交列

**Comment by coderSun20201112** [comment]
感谢老师指教，谢谢

**Comment by coderSun20201112** [comment]
感谢老师指教，谢谢
