### ISSUE TITLE
移除BC22 PSI的原因是什么

### ISSUE THREAD

**Issue by LoveZJT** [secretflow/psi#150]
如题，移除BC22 PSI的原因是什么？安全性亦或是其它原因。

**Comment by BrainWH** [comment]
是的，现在已经删掉BC22 PSI了。原因是BC22存在安全漏洞并且速度慢。

**Comment by LoveZJT** [comment]
关于BC22的安全漏洞能否提供一些资料？

**Comment by BrainWH** [comment]
您好，可以具体讲一下您这边的场景吗？您是想对比不同协议的benchmark吗？

**Comment by qxzhou1010** [comment]
> 如题，移除BC22 PSI的原因是什么？安全性亦或是其它原因。

BC22已经替换为了更快的Vole-PSI协议RR22，移除的原因是因为BC22和RR22二者的构造上高度相似，但是RR22在性能上是更优的协议，同样的构造路线上，我们选择保留目前性能最好的一个协议。

**Comment by rrsakura** [comment]
@qxzhou1010 您好，请问移除seal pir的原因是什么呢？如果是性能原因，优化后会考虑加回来吗？

**Comment by qxzhou1010** [comment]
> @qxzhou1010 您好，请问移除seal pir的原因是什么呢？如果是性能原因，优化后会考虑加回来吗？

之前seal pir实现存在一些未知的bug, 我们正在重构seal pir 的实现，会尽快将 seal pir 加回来。
