### ISSUE TITLE
PIR setup阶段出现问题

### ISSUE THREAD

**Issue by anonymous-PSI-coder** [secretflow/psi#154]
我是按照https://www.secretflow.org.cn/en/docs/psi/v0.4.0beta/user_guide/pir 中的流程来部署的，执行
`docker run -it  --rm  --network host --mount type=bind,source=/tmp/server,target=/root/server --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --cap-add=NET_ADMIN --privileged=true secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/psi-anolis8:0.1.0beta --config server/apsi_server_setup.json`代码时出现如下问题：
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--config": executable file not found in $PATH: unknown.

**Comment by wenkesong-li** [comment]
你好，你的docker版本是多少~

**Comment by anonymous-PSI-coder** [comment]
> 你好，你的docker版本是多少~
docker版本是20.10.7，我选择部署最新的psi-anolis8镜像，没有报错，显示如下：
![1721715182761](https://github.com/user-attachments/assets/856fc2ef-2a9f-4cee-a845-3d056b3d2ef6)
qing请问这样是setup执行成功了吗

**Comment by wenkesong-li** [comment]
是的~

**Comment by anonymous-PSI-coder** [comment]
> 是的~

谢谢
