### ISSUE TITLE
seal_pir性能测试

### ISSUE THREAD

**Issue by anonymous-PSI-coder** [secretflow/psi#155]
secretflow目前好像没有提供seal_pir的接口，请问应该如何测试seal_pir的性能？

**Comment by lanyy9527** [comment]
您好，SealPIR 目前没有暴露用户接口，目前只有单测：https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_pir_test.cc

**Comment by anonymous-PSI-coder** [comment]
> 您好，SealPIR 目前没有暴露用户接口，目前只有单测：https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_pir_test.cc

谢谢，我先尝试一下。

**Comment by anonymous-PSI-coder** [comment]
> 您好，SealPIR 目前没有暴露用户接口，目前只有单测：https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_pir_test.cc

您好，我刚刚接触隐语，目前只会使用PIR QuickStart中使用docker跑任务，还不太清楚怎么在隐语源码上进行测试，请问您能大致讲解一下单测的步骤吗？

**Comment by lanyy9527** [comment]
具体的使用步骤可以通过 CMake 构建和运行。可以参考：https://www.secretflow.org.cn/en/docs/psi/v0.4.0beta/getting_started#linux
您这边基于seal_pir的场景是什么呢？

**Comment by anonymous-PSI-coder** [comment]
> 具体的使用步骤可以通过 CMake 构建和运行。可以参考：https://www.secretflow.org.cn/en/docs/psi/v0.4.0beta/getting_started#linux 您这边基于seal_pir的场景是什么呢？

好的，我先试试。我这边是想试试seal_pir的性能，想和labeled psi做个比较

**Comment by anonymous-PSI-coder** [comment]
> 具体的使用步骤可以通过 CMake 构建和运行。可以参考：https://www.secretflow.org.cn/en/docs/psi/v0.4.0beta/getting_started#linux 您这边基于seal_pir的场景是什么呢？

还有一个小问题哈，就是执行labeled psi时有一个参数num_per_query。比如现在client方有100个查询，server方有100w条数据，这个num_per_query要怎么设置呢，是设置1还是100呢。如果client方有10w个查询，又该怎样设置呢？

**Comment by lanyy9527** [comment]
需要结合场景，看你是否需要查询到多个值。num_per_query，表示每个查询返回的结果数量。
设置为 1，查询的结果集中只会返回一个结果；
设置为 100，查询的结果集中包含 100 个；

**Comment by anonymous-PSI-coder** [comment]
> 需要结合场景，看你是否需要查询到多个值。num_per_query，表示每个查询返回的结果数量。 设置为 1，查询的结果集中只会返回一个结果； 设置为 100，查询的结果集中包含 100 个；

您的意思是，如果server服务器中有(alice,001),(alice,002),(alice,003)，那么num_per_query设为1时，client只能查到其中一个如(alice,001)；而num_per_query设为3时，client可以查找到(alice,001),(alice,002),(alice,003)。请问我这样理解正确吗？感谢您的耐心解答。

**Comment by lanyy9527** [comment]
不好意思，我们理解的可能有些出入，您这边使用的psi是什么版本的呢？

**Comment by anonymous-PSI-coder** [comment]
> 您这边使用的psi是什么版本的呢？

我用的docker镜像是secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/psi-anolis8:latest

**Comment by lanyy9527** [comment]
num_per_query：主要是控制每个查询请求中数据的粒度
当num_per_query=1，一个请求中1条数据，服务端处理1条；
当num_per_query=100，一个请求中100条数据，服务端处理100条；
但是目前设置为1就行，并行在计算都被打满的情况下没有太大的意义；

**Comment by anonymous-PSI-coder** [comment]
> num_per_query：主要是控制每个查询请求中数据的粒度 当num_per_query=1，一个请求中1条数据，服务端处理1条； 当num_per_query=100，一个请求中100条数据，服务端处理100条； 但是目前设置为1就行，并行在计算都被打满的情况下没有太大的意义；
原来是这样，谢谢您的解答

**Comment by anonymous-PSI-coder** [comment]
> num_per_query：主要是控制每个查询请求中数据的粒度 当num_per_query=1，一个请求中1条数据，服务端处理1条； 当num_per_query=100，一个请求中100条数据，服务端处理100条； 但是目前设置为1就行，并行在计算都被打满的情况下没有太大的意义；

再打扰您一下哈，请问图中docker部署的方式可以用于sealpir单测吗？我试了下secretflow/ubuntu-base-ci:latest这个镜像貌似找不到
![1721810271863](https://github.com/user-attachments/assets/7cf7b083-aa48-46ec-886e-8707b2681b4f)

**Comment by lanyy9527** [comment]
sealpir目前只能基于源码来做相关的测试：https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_pir_test.cc

**Comment by anonymous-PSI-coder** [comment]
> sealpir目前只能基于源码来做相关的测试：https://github.com/secretflow/psi/blob/main/psi/seal_pir/seal_pir_test.cc 通过cmake构建运行：https://www.secretflow.org.cn/en/docs/psi/v0.4.0beta/getting_started#linux

好的，非常感谢
