### ISSUE TITLE
[Feature]: pir协议咨询

### ISSUE THREAD

**Issue by yellow123Nike** [secretflow/psi#157]
### Related problem

请问，pir协议目前支持如下两种？其中第一种是什么？有具体描述吗？
![image](https://github.com/user-attachments/assets/47b8ac1e-151e-4cf0-9a89-f71d697146ab)

### Solution

pir咨询

### Alternatives

pir咨询

### Additional context

pir咨询

**Comment by aokaokd** [comment]
第一种是传统pir。目前已经下架了。现在只支持第二种

**Comment by yellow123Nike** [comment]
那labelpsi的label最长限制是多少？

**Comment by qxzhou1010** [comment]
> 那labelpsi的label最长限制是多少？

目前代码中的限制是1024-byte。

**Comment by yellow123Nike** [comment]
谢谢
