### ISSUE TITLE
[Bug]: 在不支持AVX的机器上x86机器上，编译使用PSI出现指令集问题

### ISSUE THREAD

**Issue by WandQ** [secretflow/psi#165]
### Describe the bug

我们服务器上面有一台虚拟机，由于历史原因没配置AVX2指令集，该虚拟机无法重启，使用PSI库时出现Illegal instruction (core dumped)问题
```
root@4c571785b7a7:/home/admin/psi# bazel run -c opt //psi/rr22:rr22_psi_test
WARNING: Download from https://golang.org/dl/?mode=json&include=all failed: class java.io.IOException Read timed out
INFO: Analyzed target //psi/rr22:rr22_psi_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //psi/rr22:rr22_psi_test up-to-date:
  bazel-bin/psi/rr22/rr22_psi_test
INFO: Elapsed time: 1.435s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh psi/rr22/rr22_psi_test
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //psi/rr22:rr22_psi_test
-----------------------------------------------------------------------------
external/bazel_tools/tools/test/test-setup.sh: line 328: 22620 Illegal instruction     (core dumped) "${TEST_PATH}" "$@" 2>&1
     22621 Done                    | tee -a "${XML_OUTPUT_FILE}.log"
Illegal instruction (core dumped)
``` 

### Steps To Reproduce

ubuntu20.04

model name      : QEMU Virtual CPU version 2.5+
stepping        : 1
microcode       : 0x1000065
cpu MHz         : 2500.000
cache size      : 512 KB
physical id     : 3
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl cpuid extd_apicid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpb sev vmmcall arat

### Expected behavior

希望编译出来在无AVX指令集上能用的psi库，效率慢一点没关系

### Version

v0.4.0.dev240524

### Operating system

ubuntu 20.04 x86

### Hardware Resources

8c16g

**Comment by WandQ** [comment]
> 很抱歉，psi需要avx2指令集的支持，建议更换一台支持avx2的设备

好的，那如果是国产arm架构的机器，是不是无法使用该项目的算法呢？

**Comment by aokaokd** [comment]
鲲鹏CPU是支持的，之前在鲲鹏920的设备上做过验证。

**Comment by WandQ** [comment]
> 鲲鹏CPU是支持的，之前在鲲鹏920的设备上做过验证。

fourQ也能用吗？

**Comment by anakinxc** [comment]
> > 很抱歉，psi需要avx2指令集的支持，建议更换一台支持avx2的设备
> 
> 好的，那如果是国产arm架构的机器，是不是无法使用该项目的算法呢？比如鲲鹏CPU

x86 需要 avx 和 arm 支持没有直接关系，部分库的实现在 arm 和 x86 上完全不是一套代码（比如 FourQ)
你可以尝试把 [这里](https://github.com/secretflow/yacl/blob/58bbbebd500054c71394db29bbeac2f73f35ffd1/bazel/yacl.bzl#L36) 和 [这里](https://github.com/secretflow/yacl/blob/58bbbebd500054c71394db29bbeac2f73f35ffd1/bazel/FourQlib.BUILD#L48) 的 avx 去掉，然后尝试一下可不可以 work

avx 和 avx2 都已经是超过 10 年的 instruction sets 了，现在大量的第三方库都 assume 硬件在 x86 上起码支持 avx

**Comment by WandQ** [comment]
> > > 很抱歉，psi需要avx2指令集的支持，建议更换一台支持avx2的设备
> > 
> > 
> > 好的，那如果是国产arm架构的机器，是不是无法使用该项目的算法呢？比如鲲鹏CPU
> 
> x86 需要 avx 和 arm 支持没有直接关系，部分库的实现在 arm 和 x86 上完全不是一套代码（比如 FourQ) 你可以尝试把 [这里](https://github.com/secretflow/yacl/blob/58bbbebd500054c71394db29bbeac2f73f35ffd1/bazel/yacl.bzl#L36) 和 [这里](https://github.com/secretflow/yacl/blob/58bbbebd500054c71394db29bbeac2f73f35ffd1/bazel/FourQlib.BUILD#L48) 的 avx 去掉，然后尝试一下可不可以 work
> 
> avx 和 avx2 都已经是超过 10 年的 instruction sets 了，现在大量的第三方库都 assume 硬件在 x86 上起码支持 avx

好的，明白了，验证结论x86不支持avx的情况应该是不兼容。已经通过新建一台支持AVX2的虚拟机解决问题。

感谢解答 @anakinxc @aokaokd
