### ISSUE TITLE
[Bug]: 基于secretflow/ubuntu-base-ci:latest编译报错

### ISSUE THREAD

**Issue by ssdyue** [secretflow/psi#176]
### Describe the bug

进入容器，执行 bazel build //... -c dbg，报错如下：

Starting local Bazel server and connecting to it...
INFO: Analyzed 165 targets (236 packages loaded, 26063 targets configured).
INFO: Found 165 targets...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/13daebdf0034d7b09b88f2569aaae16c/sandbox
[5,024 / 5,140] 8 actions running
    Compiling cpp/src/arrow/compute/kernels/vector_sort.cc; 33s linux-sandbox
    Compiling psi/ecdh/ecdh_psi_benchmark.cc; 32s linux-sandbox
    Compiling psi/legacy/nparty_psi_test.cc; 31s linux-sandbox
    Compiling psi/ecdh/ecdh_psi.cc; 31s linux-sandbox
    Compiling psi/legacy/nparty_psi.cc; 31s linux-sandbox
    Compiling psi/ecdh/ecdh_3pc_psi_test.cc; 30s linux-sandbox
    Compiling psi/ecdh/ecdh_3pc_psi.cc; 30s linux-sandbox
    Compiling psi/ecdh/ecdh_3pc_psi_benchmark.cc; 29s linux-sandbox

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/root/.cache/bazel/_bazel_root/13daebdf0034d7b09b88f2569aaae16c/server/jvm.out')

### Steps To Reproduce

1. 拉取secretflow/ubuntu-base-ci:latest镜像
2. docker run -d -it --name psi-dev-$(whoami)          --mount type=bind,source="$(pwd)",target=/home/admin/dev/          -w /home/admin/dev          --cap-add=SYS_PTRACE --security-opt seccomp=unconfined          --cap-add=NET_ADMIN          --privileged=true          --entrypoint="bash"          secretflow/ubuntu-base-ci:latest
3. 进入容器编译

### Expected behavior

期望编译成功

### Version

master

### Operating system

mac上镜像部署

### Hardware Resources

8c16g

**Comment by 6fj** [comment]
请尝试一下

```
bazel build //... -c dbg --jobs 4
```

降低一下bazel编译的并行度
