### ISSUE TITLE
[Bug]: 编译报错bazel build //psi:psi_xxx_test

### ISSUE THREAD

**Issue by neaos** [secretflow/psi#187]
### Describe the bug

编译报错：
root@hezhangjie:/opt/isafelinke/goProject/psi# bazel build //psi:psi_datasource_test
INFO: Analyzed target //psi:psi_datasource_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /opt/isafelinke/goProject/psi/psi/BUILD.bazel:162:12: Linking psi/psi_datasource_test failed: (Exit 1): gcc failed: error executing command (from target //psi:psi_datasource_test) /usr/bin/gcc @bazel-out/k8-fastbuild/bin/psi/psi_datasource_test-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoData.a(RecordSet.cpp.o):RecordSet.cpp:function Poco::Dynamic::VarHolderImpl<Poco::DateTime>::convert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const: error: undefined reference to 'Poco::DateTimeFormatter::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Poco::DateTime const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoData.a(RecordSet.cpp.o):RecordSet.cpp:function Poco::Dynamic::VarHolderImpl<Poco::Data::Time>::convert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const: error: undefined reference to 'Poco::DateTimeFormatter::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Poco::DateTime const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoData.a(RecordSet.cpp.o):RecordSet.cpp:function Poco::Dynamic::VarHolderImpl<Poco::Data::Date>::convert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const: error: undefined reference to 'Poco::DateTimeFormatter::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Poco::DateTime const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoData.a(RowFilter.cpp.o):RowFilter.cpp:function Poco::Data::RowFilter::RowFilter(Poco::Data::RecordSet*): error: undefined reference to 'Poco::RefCountedObject::RefCountedObject()'

![image](https://github.com/user-attachments/assets/22688aa3-29c3-481c-826a-8727cf134c46)

### Steps To Reproduce

1

### Expected behavior

![image](https://github.com/user-attachments/assets/f329e24d-17f8-45c5-b113-5ce7b720987a)

### Version

v0.4.3.dev240913

### Operating system

ubuntu 20.04.6

### Hardware Resources

4c16g

**Comment by lanyy9527** [comment]
您好，请检查下开发环境是否完整：Install gcc>=11.2, cmake>=3.26, ninja, nasm>=2.15, python>=3.8, bazel, golang, xxd, lld
