### ISSUE TITLE
SealPIR API

### ISSUE THREAD

**Issue by anonymous-PSI-coder** [secretflow/psi#198]
最新版本中SealPIR已经回归了，请问现在SealPIR提供相关的API吗？

**Comment by wangzul** [comment]
方便说一下SealPIR使用场景吗，数据量，key多大，label多大，网络情况。也可以讲一下对于SealPIR的建议。

**Comment by anonymous-PSI-coder** [comment]
> 方便说一下SealPIR使用场景吗，数据量，key多大，label多大，网络情况。也可以讲一下对于SealPIR的建议。

阅读论文时发现SealPIR的性能较好，恰好隐语提供了SealPIR的实现，所以想借助隐语提供的实现进行实验，数据量是1-100w，label 288B，LAN。希望SealPIR可以推出API吧。还有一个建议是Labeled PSI能否给一个调参的建议，不太清楚除了benchmark的数据应该怎么调整参数。
