### ISSUE TITLE
Repeated Keys for PIR

### ISSUE THREAD

**Issue by anonymous-PSI-coder** [secretflow/psi#204]
您好，请问对于server数据库存在重复key的情况，现有的PIR算法是否支持将同一个key对应的所有行都查询出来？

**Comment by BrainWH** [comment]
当前不支持。APSI目前分为Setup Stage和Online stage，如果存在重复数据，在Setup Stage就会失败。可以参考https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.2b0/user_guide/pir#prepare-data-and-config

**Comment by anonymous-PSI-coder** [comment]
> 当前不支持。APSI目前分为Setup Stage和Online stage，如果存在重复数据，在Setup Stage就会失败。可以参考https://www.secretflow.org.cn/zh-CN/docs/psi/v0.4.2b0/user_guide/pir#prepare-data-and-config

感谢您的回复。

**Comment by anonymous-PSI-coder** [comment]
看了下readme中有提到未来将有keyword PIR到index PIR的转换，请问这个功能是否可以通过这个转换实现呢？

**Comment by BrainWH** [comment]
确实会有keyword PIR到index PIR的转换。但是您说的将同一个key对应的所有行都查询出来这个功能和算法的实现没有关系，可以通过预处理实现，比如把重复键的key对应的tag 连成一个长的tag，查询出来后再拆开。

**Comment by anonymous-PSI-coder** [comment]
> 确实会有keyword PIR到index PIR的转换。但是您说的将同一个key对应的所有行都查询出来这个功能和算法的实现没有关系，可以通过预处理实现，比如把重复键的key对应的tag 连成一个长的tag，查询出来后再拆开。

理解了，感谢
