### ISSUE TITLE
关于隐语实现的ECDH-OPRF协议问题请教

### ISSUE THREAD

**Issue by JiPZou** [secretflow/psi#53]
我看文档中说ECDH-OPRF协议，是基于RA18的第三章
![084753af398fc4e19d3dad3ce5fd6da](https://github.com/secretflow/psi/assets/23051026/8693fb2c-e621-4fd2-bf95-8dfbc70bbbbf)

但是，RA18的第三章实现的算法，并没有使用OPRF。
![f8c26afe0d6c6929fff9ea6dc420b0a](https://github.com/secretflow/psi/assets/23051026/766b90a6-bf5d-4fb8-94a6-7aa81e931441)

请问咱们这边是自己添加的吗？还是基于什么论文实现的？

**Comment by Chrisdehe** [comment]
可以参考下这个推文：https://mp.weixin.qq.com/s/TRPHMWUD3VKpZPzLFqnJXA
