### ISSUE TITLE
cryptor中的椭圆曲线算子没有实现mask的逆方法，准备自己实现一个，但是出现了一些问题

### ISSUE THREAD

**Issue by WandQ** [secretflow/psi#54]
我想实现ECDH-PSI的如下版本：
1.接收方集合加密后发送给发送方（aG）
2.发送方将收到的加密后返还给接收方（abG）
3.接收方解密收到的数据(a^ abG->bG)
4.发送方将自己的集合加密后发送给接收方
5.对比得到交集

我基于sm2_cryptor.cc中的EccMask进行实验时出现了a^ abG 不等于 bG 的情况，实验代码（sm2_cryptor.cc中的第35行）如下：
```c++
auto mask_functor = [this](const Item& in, Item& out) {
    BnCtxPtr bn_ctx(yacl::CheckNotNull(BN_CTX_new()));

    EcGroupSt ec_group(GetEcGroupId(curve_type_));

    EcPointSt ec_point(ec_group);

    EC_POINT_oct2point(ec_group.get(), ec_point.get(),
                       reinterpret_cast<const unsigned char*>(in.data()),
                       in.size(), bn_ctx.get());

    BigNumSt bn_sk;
    bn_sk.FromBytes(
        absl::string_view(reinterpret_cast<const char*>(&this->private_key_[0]),
                          kEccKeySize),
        ec_group.bn_p);

    Item input_point;
    ec_point.ToBytes(absl::MakeSpan(
        reinterpret_cast<uint8_t*>(input_point.data()), input_point.size()));
    std::cout << "input_point:" << input_point.data() << std::endl;
    // pointmul
    BigNumSt bn_sk_v = bn_sk.Inverse(ec_group.bn_p);  // 拿到私钥模逆

    EcPointSt ec_point2 = ec_point.PointMul(ec_group, bn_sk);

    EcPointSt ec_point3 = ec_point2.PointMul(ec_group, bn_sk_v);  // 乘私钥的模逆

    ec_point3.ToBytes(
        absl::MakeSpan(reinterpret_cast<uint8_t*>(out.data()), out.size()));
    std::cout << "out:" << out.data() << std::endl;
  };
``` 

输出结果：
input_point:ni!���z��
                     ���ۺ;e6^���E��O"�^�
out:�8R��$�׋��A�V)tz�%$�K�9Ǩ�
                             ��

理论上ec_point应该等于ec_point3，但是实际不是，不知道是什么原因，期待解答。

**Comment by Chrisdehe** [comment]
@WandQ 
hi 可以参考ec-oprf的代码哈～
https://github.com/secretflow/psi/blob/main/psi/psi/core/ecdh_oprf/basic_ecdh_oprf.cc

**Comment by WandQ** [comment]
> @WandQ hi 可以参考ec-oprf的代码哈～ https://github.com/secretflow/psi/blob/main/psi/psi/core/ecdh_oprf/basic_ecdh_oprf.cc

谢谢，我看到unblind方法了，但是遇到了一个困惑。
https://github.com/secretflow/psi/blob/main/psi/psi/core/ecdh_oprf/basic_ecdh_oprf.cc 中的EcPointMul方法
```
std::string EcPointMul(absl::string_view sk_bytes,
                       absl::string_view point_bytes, int ec_group_nid) {
...
  bn_sk.FromBytes(absl::string_view(static_cast<const char *>(sk_bytes.data()),
                                    sk_bytes.length()),
                  ec_group.bn_n);
...
}
``` 
bn_sk导入用的ec_group.**bn_n**，包括取逆也是用的ec_group.bn_n，
而https://github.com/secretflow/psi/blob/main/psi/psi/cryptor/sm2_cryptor.cc中的void Sm2Cryptor::EccMask()方法使用的bn_sk.FromBytes(
        absl::string_view(reinterpret_cast<const char*>(&this->private_key_[0]),
                          kEccKeySize),
        ec_group.bn_p);
bn_sk导入用的ec_group.**bn_p**。
为什么不一致呢？

**Comment by zhanglei486** [comment]
sm2_cryptor.cc 中代码有bug，应该是bn_n，我们在后续的版本中修复
bn_n是ec group 阶
bn_p是ec的GFp域
