### ISSUE TITLE
PSI Quick Start with v2 API 报错

### ISSUE THREAD

**Issue by GreyJeremyji** [secretflow/psi#64]
报错如下
(base) root@k8s-node1:/approot1/secretflow-learn/quikstart# docker run -it  --rm  --network host --mount type=bind,source=/tmp/receiver,target=/root/receiver -w /root  --cap-a                                                                                                           dd=SYS_PTRACE --security-opt seccomp=unconfined --cap-add=NET_ADMIN --privileged=true secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/psi-anolis8:latest bash -c "./                                                                                                           main --config receiver/receiver.config"
[2024-01-25 16:23:45.540] [info] [main.cc:44] SecretFlow PSI Library v0.2.0.dev240123 Copyright 2023 Ant Group Co., Ltd.
terminate called after throwing an instance of 'yacl::EnforceNotMet'
  what():  [Enforce fail at psi/main.cc:70] status.ok(). Launch config JSON string couldn't be parsed: {
    "psi_config": {
        "protocol_config": {
            "protocol": "PROTOCOL_KKRT",
            "role": "ROLE_RECEIVER",
            "broadcast_result": true
        },
        "input_config": {
            "type": "IO_TYPE_FILE_CSV",
            "path": "/root/receiver/receiver_input.csv"
        },
        "output_config": {
            "type": "IO_TYPE_FILE_CSV",
            "path": "/root/receiver/receiver_output.csv"
        },
        "keys": [
            "id0",
            "id1"
        ],
        "debug_options": {
            "trace_path": "/root/receiver/receiver.trace"
        },
        "link_config": {
            "parties": [
                {
                    "id": "receiver",
                    "host": "127.0.0.1:5300"
                },
                {
                    "id": "sender",
                    "host": "127.0.0.1:5400"
                }
            ]
        }
    },
    "self_link_party": "receiver"
}
Stacktrace:
#0 __libc_start_main+0x7f503283acf3

**Comment by zimu-yuxi** [comment]
看着像json格式错误，看下复制的代码，是不是少了{

**Comment by 6fj** [comment]
```
{
    "psi_config": {
        "protocol_config": {
            "protocol": "PROTOCOL_KKRT",
            "role": "ROLE_RECEIVER",
            "broadcast_result": true
        },
        "input_config": {
            "type": "IO_TYPE_FILE_CSV",
            "path": "/root/receiver/receiver_input.csv"
        },
        "output_config": {
            "type": "IO_TYPE_FILE_CSV",
            "path": "/root/receiver/receiver_output.csv"
        },
        "keys": [
            "id0",
            "id1"
        ],
        "debug_options": {
            "trace_path": "/root/receiver/receiver.trace"
        }
    },
    "self_link_party": "receiver",
    "link_config": {
        "parties": [
            {
                "id": "receiver",
                "host": "127.0.0.1:5300"
            },
            {
                "id": "sender",
                "host": "127.0.0.1:5400"
            }
        ]
    }
}
```

**Comment by GreyJeremyji** [comment]
> ```
> {
>     "psi_config": {
>         "protocol_config": {
>             "protocol": "PROTOCOL_KKRT",
>             "role": "ROLE_RECEIVER",
>             "broadcast_result": true
>         },
>         "input_config": {
>             "type": "IO_TYPE_FILE_CSV",
>             "path": "/root/receiver/receiver_input.csv"
>         },
>         "output_config": {
>             "type": "IO_TYPE_FILE_CSV",
>             "path": "/root/receiver/receiver_output.csv"
>         },
>         "keys": [
>             "id0",
>             "id1"
>         ],
>         "debug_options": {
>             "trace_path": "/root/receiver/receiver.trace"
>         }
>     },
>     "self_link_party": "receiver",
>     "link_config": {
>         "parties": [
>             {
>                 "id": "receiver",
>                 "host": "127.0.0.1:5300"
>             },
>             {
>                 "id": "sender",
>                 "host": "127.0.0.1:5400"
>             }
>         ]
>     }
> }
> ```

找到原因了，我提个PR
