### ISSUE TITLE
[Bug]: psi_test数据容量问题

### ISSUE THREAD

**Issue by ChongMa1** [secretflow/psi#76]
### Issue Type

Usability

### Modules Involved

PSI

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.7.0b0

### OS Platform and Distribution

centos 7

### Python Version

3.8

### Current Behavior?

我修改了bob.csv，扩大了数据量，显示出错，self.assertEqual( 数1 != 数2)。我跟着代码from .psi_pb2 import(  # type: ignoreBucketPsiConfig,CurveType,InputParams,MemoryPsiConfig,OutputParams,PsiResultReport,PsiType,)，没有找到这个psi_pb2这个文件。

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by Chrisdehe** [comment]
@ChongMa1 可以添加个微信技术支持微信哈（secretflow02）可以深入交流下技术实现。
